//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace productStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_qty { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> product_cat { get; set; }
        public Nullable<int> product_brand { get; set; }
    
        public virtual tbl_brands tbl_brands { get; set; }
        public virtual tbl_category tbl_category { get; set; }
    }
}
